name: Deploy Site

on:
    # Runs on pushes targeting the default branch
    push:
      branches: [ main ]
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages    
permissions:
    contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: statiq-cleanblog-demo
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' # SDK Version to use.
    - run: dotnet run -- deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
